name: Update on ledger release
on:
  repository_dispatch:
    types: [fluree-ledger-release]

jobs:
  debug:
    runs-on: macos-latest
    steps:
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - id: get-version
        run: |
          version=$(echo ${{ github.event.client_payload.release.tag_name }} | cut -c 2-)
          echo "::set-output name=version::$version"
      - id: get-class-name
        run: |
          class=$(./version-to-class.sh ${{ steps.get-version.outputs.version }})
          echo "::set-output name=class::$class"
      - name: Create versioned formula for release
        if: ${{ github.event.client_payload.action == 'published' && startsWith(github.event.client_payload.release.tag_name, 'v') }}
        env:
          FLUREE_VERSION: ${{ steps.get-version.outputs.version }}
          FLUREE_HOMEBREW_CLASS: ${{ steps.get-class-name.outputs.class }}
        run: |
          sed "s/class Flureedb/class ${FLUREE_HOMEBREW_CLASS}/" Formula/flureedb.rb > Formula/flureedb@${FLUREE_VERSION}.rb
          git add .
          git commit -m "Release formula for v${FLUREE_VERSION}"
          git push
      - name: Delete versioned formula
        if: ${{ github.event.client_payload.action == 'deleted' || github.event.client_payload.action == 'unpublished' }}
        env:
          FLUREE_VERSION: ${{ steps.get-version.outputs.version }}
        run: |
          rm Formula/flureedb@${FLUREE_VERSION}.rb
          git rm Formula/flureedb@${FLUREE_VERSION}.rb
          git commit -m "Delete formula for v${FLUREE_VERSION}"
          git push
