name: Update on ledger release
on:
  repository_dispatch:
    types: [fluree-ledger-release]

jobs:
  debug:
    runs-on: macos-latest
    steps:
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  release:
    runs-on: macos-latest
    steps:
      - name: Create specific version for release
        run: printenv
